### PR TITLE
feat: Update cluster_autoscaler.tf

### PR DESCRIPTION
**Pull request by illegalnumbers**
Update acluster autoscaler to include 1.24

### CODE REVIEW

**Review by martijngonlag — APPROVED** [review]

**Comment by ignacioli** [comment]
@illegalnumbers we should support more versions in advance, according to [argo](https://github.com/streamnative/argo/blob/master/charts/poolmember/values.yaml#L71-L88). The minor version is not so import but it is preferred to use the latest one.

**Comment by illegalnumbers** [comment]
@dpappa can you take a look here, we probably should update this yet again to include non EOL versions as I think 1.24 is no longer supported

**Comment by dpappa** [comment]
I added/removed k8s versions based on what's available and supported in both EKS and cluster-autoscaler in [this PR](https://github.com/streamnative/terraform-aws-cloud/pull/120).

**Comment by illegalnumbers** [comment]
K i will close this it is superseeded by #120

**Pull request closed without merging**
